# Generated by Django 6.0.5 on 2026-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_Featured',
            field=models.BooleanField(default=False),
        ),
    ]
