# Generated by Django 6.0.5 on 2026-05-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_Featured',
            new_name='is_featured',
        ),
    ]
