# Generated by Django 6.0.5 on 2026-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Débutant', max_length=200),
        ),
    ]
