# Generated by Django 6.0.5 on 2026-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Prévu'), ('in_progress', 'En cours'), ('completed', 'Terminé')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.CharField(max_length=255),
        ),
    ]
