# Generated by Django 6.0.5 on 2026-05-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_project_description_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Fontend', 'Fontend'), ('Backend', 'Backend'), ('General', 'General')], default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avancé')], default='Débutant', max_length=200),
        ),
    ]
